version: '3.8'

services:
  ros2-desktop:
    build: .
    platform: linux/arm64
    ports:
      - "6080:80"
    shm_size: '512m'
    volumes:
      - ~/Projects/ros2-vnc:/root/Projects
      - ./src:/root/Projects/ros2_mezzotint/src
      - ./Makefile:/root/Projects/ros2_mezzotint/Makefile
    container_name: ros2_desktop_vnc
