version: '3.8'

services:
  ros2-desktop:
    build: .
    platform: linux/arm64
    ports:
      - "6080:80"
    shm_size: '512m'
    volumes:
      - ./:/home/ubuntu/Projects/ros2_mezzotint  # Mount the project root directly
    container_name: ros2_desktop_vnc
    user: "${UID}:${GID}"  # Optional: Map host user permissions
