# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cobot630_arm_controller
    - cobot_tool_controller

  cobot630_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
    action_ns: follow_joint_trajectory
    default: true
  
  cobot_tool_controller:
    type: FollowJointTrajectory
    joints:
      - joint5
    action_ns: follow_joint_trajectory