# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cobot630_arm_controller
    - cobot_tool_controller

  cobot630_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1_to_base
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
    action_ns: follow_joint_trajectory
    default: true
  
  cobot_tool_controller:
    type: FollowJointTrajectory
    joints:
      - joint6_to_joint5
    action_ns: follow_joint_trajectory